//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceEMI
    {
        public int emiId { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> staffid { get; set; }
    
        public virtual AdvanceRequest AdvanceRequest { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
