//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequest
    {
        public AdvanceRequest()
        {
            this.AdvanceEMIs = new HashSet<AdvanceEMI>();
        }
    
        public int requestId { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> willPayEMI { get; set; }
        public Nullable<System.DateTime> requestedDate { get; set; }
        public Nullable<bool> isApprove { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<int> paidMonth { get; set; }
        public Nullable<int> paidYear { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ICollection<AdvanceEMI> AdvanceEMIs { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
