//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        public AspNetRole()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
