//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignShift
    {
        public int ShiftassignId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Fromdate { get; set; }
        public Nullable<int> Todate { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<bool> IsAllot { get; set; }
    }
}
