//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRequest
    {
        public int transId { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public Nullable<System.DateTime> attendDate { get; set; }
        public Nullable<int> inOutMode { get; set; }
        public string narration { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
