//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int BankinfoId { get; set; }
        public string BankName { get; set; }
        public string BankIfsc { get; set; }
        public string AccountNo { get; set; }
        public string HolderName { get; set; }
        public string Branch { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> StaffId { get; set; }
    }
}
