//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonu
    {
        public int bonusId { get; set; }
        public Nullable<System.DateTime> tranDate { get; set; }
        public Nullable<int> bonusMonth { get; set; }
        public Nullable<int> bouusYear { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string narration { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
