//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BufferTimeSetting
    {
        public int BufferId { get; set; }
        public Nullable<int> EarlyIn { get; set; }
        public Nullable<int> EarlyOut { get; set; }
        public Nullable<int> LateIn { get; set; }
        public Nullable<int> LateOut { get; set; }
        public Nullable<int> firmid { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
