//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompansationTran
    {
        public int compId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<bool> isApprove { get; set; }
        public Nullable<bool> isRejected { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
