//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerAssinged
    {
        public ComputerAssinged()
        {
            this.DurationTrans = new HashSet<DurationTran>();
        }
    
        public int pcAssignedId { get; set; }
        public Nullable<int> staffId { get; set; }
        public string IPAddress { get; set; }
        public string MachineName { get; set; }
        public string Username { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ICollection<DurationTran> DurationTrans { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
