//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int configId { get; set; }
        public Nullable<decimal> schoolCode { get; set; }
        public Nullable<bool> isStudent { get; set; }
    }
}
