//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public Degree()
        {
            this.StaffEducations = new HashSet<StaffEducation>();
        }
    
        public int degreeId { get; set; }
        public string degreeName { get; set; }
    
        public virtual ICollection<StaffEducation> StaffEducations { get; set; }
    }
}
