//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.StaffDesignations = new HashSet<StaffDesignation>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int designationId { get; set; }
        public string designation1 { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ICollection<StaffDesignation> StaffDesignations { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
