//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DurationTran
    {
        public int durationTranId { get; set; }
        public Nullable<System.DateTime> durationDate { get; set; }
        public Nullable<int> assignedId { get; set; }
        public string machineName { get; set; }
        public string IPAddress { get; set; }
        public string userName { get; set; }
        public string Status { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ComputerAssinged ComputerAssinged { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
