//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditPermission
    {
        public int PermissionId { get; set; }
        public Nullable<bool> GeneralInfo { get; set; }
        public Nullable<bool> AppAttendance { get; set; }
        public Nullable<bool> ManualAttendance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> LeaveApproval { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsProbationLeaveApp { get; set; }
    }
}
