//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPFDetail
    {
        public int EpfId { get; set; }
        public string EpfAccountno { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Staffid { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> firmid { get; set; }
    }
}
