//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiFamily
    {
        public int esifamid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string relationship { get; set; }
        public Nullable<bool> reside { get; set; }
        public string town { get; set; }
        public string state { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<int> firmid { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<int> esiinfoid { get; set; }
    }
}
