//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiInfo
    {
        public int esiid { get; set; }
        public Nullable<int> staffid { get; set; }
        public string fathername { get; set; }
        public string peraddress { get; set; }
        public string pin { get; set; }
        public string branchoffice { get; set; }
        public Nullable<System.DateTime> dateofappoint { get; set; }
        public string preinsuranceno { get; set; }
        public string preempolyecode { get; set; }
        public string nomineename { get; set; }
        public string relationship { get; set; }
        public string nomaddress { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public string corponame { get; set; }
        public string corpinsno { get; set; }
        public string corpfathername { get; set; }
        public string corpbranchoffice { get; set; }
        public Nullable<System.DateTime> dateofentry { get; set; }
        public Nullable<System.DateTime> corpdob { get; set; }
        public string dispensary { get; set; }
        public Nullable<int> firmid { get; set; }
        public string Employeraddressname { get; set; }
        public string CurEmployeraddressname { get; set; }
        public string corpnameaddresscode { get; set; }
        public string corpDispensary { get; set; }
    }
}
