//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailureSignupFirm
    {
        public int firmId { get; set; }
        public string firmName { get; set; }
        public string logo { get; set; }
        public string flatNo { get; set; }
        public string street { get; set; }
        public string area { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public Nullable<bool> ipFiltering { get; set; }
        public Nullable<System.DateTime> validDate { get; set; }
        public Nullable<System.DateTime> renewalDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string UniversalId { get; set; }
        public string CompanyId { get; set; }
        public string Noofemp { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string paymethod { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string currency { get; set; }
        public string package { get; set; }
    }
}
