//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackFormMaster
    {
        public FeedbackFormMaster()
        {
            this.QuestionAssigments = new HashSet<QuestionAssigment>();
            this.TblRatings = new HashSet<TblRating>();
            this.TblFormAssignments = new HashSet<TblFormAssignment>();
        }
    
        public int FeedbackId { get; set; }
        public string Title { get; set; }
        public string Duration { get; set; }
        public Nullable<int> firmid { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual ICollection<QuestionAssigment> QuestionAssigments { get; set; }
        public virtual ICollection<TblRating> TblRatings { get; set; }
        public virtual ICollection<TblFormAssignment> TblFormAssignments { get; set; }
    }
}
