//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmInfo
    {
        public FirmInfo()
        {
            this.AdvanceEMIs = new HashSet<AdvanceEMI>();
            this.AdvanceRequests = new HashSet<AdvanceRequest>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.AttendanceRequests = new HashSet<AttendanceRequest>();
            this.AttendanceStaffs = new HashSet<AttendanceStaff>();
            this.CompansationRequests = new HashSet<CompansationRequest>();
            this.CompansationTrans = new HashSet<CompansationTran>();
            this.ComputerAssingeds = new HashSet<ComputerAssinged>();
            this.Departments = new HashSet<Department>();
            this.Designations = new HashSet<Designation>();
            this.DurationTrans = new HashSet<DurationTran>();
            this.EventLogs = new HashSet<EventLog>();
            this.Events = new HashSet<Event>();
            this.GeneratedSalaries = new HashSet<GeneratedSalary>();
            this.Holidays = new HashSet<Holiday>();
            this.LeaveBalances = new HashSet<LeaveBalance>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.LeaveTypes = new HashSet<LeaveType>();
            this.MachineConfigures = new HashSet<MachineConfigure>();
            this.MonthlyAttenDetails = new HashSet<MonthlyAttenDetail>();
            this.MonthlyTTargets = new HashSet<MonthlyTTarget>();
            this.notices = new HashSet<notice>();
            this.OptionalHolidays = new HashSet<OptionalHoliday>();
            this.TblPayheadTypes = new HashSet<TblPayheadType>();
            this.PayrollConfigs = new HashSet<PayrollConfig>();
            this.PreviousEduInfoes = new HashSet<PreviousEduInfo>();
            this.SalaryStructures = new HashSet<SalaryStructure>();
            this.SalaryVariables = new HashSet<SalaryVariable>();
            this.Staffs = new HashSet<Staff>();
            this.StaffCTCs = new HashSet<StaffCTC>();
            this.StaticIPs = new HashSet<StaticIP>();
            this.Structurepermissions = new HashSet<Structurepermission>();
            this.TblLoginCounters = new HashSet<TblLoginCounter>();
            this.VariableSettings = new HashSet<VariableSetting>();
            this.Weekends = new HashSet<Weekend>();
        }
    
        public int firmId { get; set; }
        public string firmName { get; set; }
        public string logo { get; set; }
        public string flatNo { get; set; }
        public string street { get; set; }
        public string area { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public Nullable<bool> ipFiltering { get; set; }
        public Nullable<System.DateTime> validDate { get; set; }
        public Nullable<System.DateTime> renewalDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string UniversalId { get; set; }
        public string CompanyId { get; set; }
        public string Noofemp { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string paymethod { get; set; }
        public string currency { get; set; }
        public string package { get; set; }
    
        public virtual ICollection<AdvanceEMI> AdvanceEMIs { get; set; }
        public virtual ICollection<AdvanceRequest> AdvanceRequests { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<AttendanceRequest> AttendanceRequests { get; set; }
        public virtual ICollection<AttendanceStaff> AttendanceStaffs { get; set; }
        public virtual ICollection<CompansationRequest> CompansationRequests { get; set; }
        public virtual ICollection<CompansationTran> CompansationTrans { get; set; }
        public virtual ICollection<ComputerAssinged> ComputerAssingeds { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Designation> Designations { get; set; }
        public virtual ICollection<DurationTran> DurationTrans { get; set; }
        public virtual ICollection<EventLog> EventLogs { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<GeneratedSalary> GeneratedSalaries { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<LeaveType> LeaveTypes { get; set; }
        public virtual ICollection<MachineConfigure> MachineConfigures { get; set; }
        public virtual ICollection<MonthlyAttenDetail> MonthlyAttenDetails { get; set; }
        public virtual ICollection<MonthlyTTarget> MonthlyTTargets { get; set; }
        public virtual ICollection<notice> notices { get; set; }
        public virtual ICollection<OptionalHoliday> OptionalHolidays { get; set; }
        public virtual ICollection<TblPayheadType> TblPayheadTypes { get; set; }
        public virtual ICollection<PayrollConfig> PayrollConfigs { get; set; }
        public virtual ICollection<PreviousEduInfo> PreviousEduInfoes { get; set; }
        public virtual ICollection<SalaryStructure> SalaryStructures { get; set; }
        public virtual ICollection<SalaryVariable> SalaryVariables { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<StaffCTC> StaffCTCs { get; set; }
        public virtual ICollection<StaticIP> StaticIPs { get; set; }
        public virtual ICollection<Structurepermission> Structurepermissions { get; set; }
        public virtual ICollection<TblLoginCounter> TblLoginCounters { get; set; }
        public virtual ICollection<VariableSetting> VariableSettings { get; set; }
        public virtual ICollection<Weekend> Weekends { get; set; }
    }
}
