//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedSalaryVariable
    {
        public int TranId { get; set; }
        public Nullable<int> monthlyAttenDetailId { get; set; }
        public Nullable<int> variableId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> isEarnings { get; set; }
        public Nullable<bool> isDuductions { get; set; }
        public string HeadName { get; set; }
        public string Narration { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual MonthlyAttenDetail MonthlyAttenDetail { get; set; }
        public virtual VariableSetting VariableSetting { get; set; }
    }
}
