//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedSalary
    {
        public int generatedSalId { get; set; }
        public Nullable<int> ctcId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> attendDays { get; set; }
        public Nullable<decimal> absenceDays { get; set; }
        public Nullable<decimal> leaveDays { get; set; }
        public string generatedBy { get; set; }
        public Nullable<System.DateTime> generatedDate { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual StaffCTC StaffCTC { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
