//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InActiveResion
    {
        public InActiveResion()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int inActiveResionId { get; set; }
        public string resion { get; set; }
        public Nullable<bool> isOnlyWorkingDays { get; set; }
        public Nullable<bool> isLeavesPayble { get; set; }
        public Nullable<int> veriableId { get; set; }
        public Nullable<bool> isHolidayPayble { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual VariableSetting VariableSetting { get; set; }
    }
}
