//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int Id { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> leaveTypeId { get; set; }
        public Nullable<decimal> noOfLeaves { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<System.DateTime> systemDate { get; set; }
        public Nullable<int> addedBy { get; set; }
        public string Narration { get; set; }
        public string status { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
