//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int tranId { get; set; }
        public Nullable<int> lTypeId { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string sesionDateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public string sesionDateTo { get; set; }
        public Nullable<decimal> totalCounts { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string status { get; set; }
        public string approvedBY { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public Nullable<System.DateTime> rejoing { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<bool> DeductStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
