//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.LeaveBalances = new HashSet<LeaveBalance>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.LeavePassbooks = new HashSet<LeavePassbook>();
            this.TblLeaveRecords = new HashSet<TblLeaveRecord>();
            this.LeaveRecordNews = new HashSet<LeaveRecordNew>();
        }
    
        public int leaveTypeId { get; set; }
        public string LeaveType1 { get; set; }
        public Nullable<decimal> counts { get; set; }
        public Nullable<decimal> perMonthLeavesAdd { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<LeavePassbook> LeavePassbooks { get; set; }
        public virtual ICollection<TblLeaveRecord> TblLeaveRecords { get; set; }
        public virtual ICollection<LeaveRecordNew> LeaveRecordNews { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
