//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavePassbook
    {
        public int LptranId { get; set; }
        public Nullable<int> LplTypeId { get; set; }
        public Nullable<int> LpstaffId { get; set; }
        public Nullable<System.DateTime> LpdateFrom { get; set; }
        public string LpsesionDateFrom { get; set; }
        public Nullable<System.DateTime> LpdateTo { get; set; }
        public string LpsesionDateTo { get; set; }
        public Nullable<decimal> LptotalCounts { get; set; }
        public Nullable<System.DateTime> LpcreatedDate { get; set; }
        public string Lpstatus { get; set; }
        public string LpapprovedBY { get; set; }
        public Nullable<System.DateTime> LpapprovalDate { get; set; }
        public Nullable<System.DateTime> Lprejoing { get; set; }
        public Nullable<int> LpfirmId { get; set; }
        public Nullable<bool> LpDeductStatus { get; set; }
        public Nullable<int> LeaveRecordIds { get; set; }
        public Nullable<decimal> totalLeavess { get; set; }
        public Nullable<int> LplrequestId { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual TblLeaveRecord TblLeaveRecord { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
