//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineConfigure
    {
        public int id { get; set; }
        public string IPAddress { get; set; }
        public string Port { get; set; }
        public Nullable<int> firmId { get; set; }
        public string SerialKey { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
