//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberattendaceConfig
    {
        public int ConfigId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> Machineid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> FirmId { get; set; }
        public Nullable<int> FingureId { get; set; }
    }
}
