//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int menuItemId { get; set; }
        public string itemName { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> menuId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
