//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyAttenDetail
    {
        public MonthlyAttenDetail()
        {
            this.GeneratedSalaryVariables = new HashSet<GeneratedSalaryVariable>();
        }
    
        public int monthlyAttenDetailId { get; set; }
        public Nullable<int> tranMonth { get; set; }
        public Nullable<int> tranYearyear { get; set; }
        public Nullable<System.DateTime> tranDate { get; set; }
        public Nullable<int> totalMonthDays { get; set; }
        public Nullable<decimal> PresentDays { get; set; }
        public Nullable<decimal> usedCompansation { get; set; }
        public Nullable<decimal> earnCompansation { get; set; }
        public string transactionBy { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<decimal> weeklyOff { get; set; }
        public Nullable<decimal> absent { get; set; }
        public Nullable<decimal> paidLeaves { get; set; }
        public Nullable<decimal> currentMonthCompansation { get; set; }
        public Nullable<decimal> preMonthCompansation { get; set; }
        public Nullable<decimal> monthlyPaidLeaves { get; set; }
        public Nullable<int> Holidays { get; set; }
        public Nullable<int> ctcId { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<decimal> paybleDays { get; set; }
        public string generatedBySalary { get; set; }
        public Nullable<System.DateTime> generatedDateSalary { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> shiftcount { get; set; }
        public Nullable<decimal> workdaypresent { get; set; }
        public Nullable<decimal> physicalpresents { get; set; }
        public Nullable<decimal> MonthWorkingDay { get; set; }
        public Nullable<decimal> Totaltime { get; set; }
        public Nullable<decimal> Machinetime { get; set; }
        public Nullable<decimal> OvertimeUndertime { get; set; }
        public Nullable<decimal> ExtraEarning { get; set; }
        public Nullable<decimal> ExtraDeduction { get; set; }
        public Nullable<decimal> AbsentAmt { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<decimal> OvertimeAmt { get; set; }
        public Nullable<decimal> UndertimeAmt { get; set; }
        public Nullable<int> Structureid { get; set; }
    
        public virtual ICollection<GeneratedSalaryVariable> GeneratedSalaryVariables { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
