//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyTTarget
    {
        public int trgId { get; set; }
        public Nullable<int> trgValue { get; set; }
        public Nullable<int> trgMonth { get; set; }
        public Nullable<int> trgYear { get; set; }
        public int firmid { get; set; }
        public string deptName { get; set; }
        public Nullable<int> deptid { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
