//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice
    {
        public int noticeId { get; set; }
        public string Title { get; set; }
        public string narration { get; set; }
        public Nullable<System.DateTime> noticeDisplayUpto { get; set; }
        public Nullable<System.DateTime> systemDatetime { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
