//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalHoliday
    {
        public OptionalHoliday()
        {
            this.OptionalHolidayTrans = new HashSet<OptionalHolidayTran>();
        }
    
        public int optionalId { get; set; }
        public string optionalHolidayName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual ICollection<OptionalHolidayTran> OptionalHolidayTrans { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
