//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalHolidayTran
    {
        public int TranId { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> optionalholidayId { get; set; }
        public Nullable<bool> isApprove { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual OptionalHoliday OptionalHoliday { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
