//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollConfig
    {
        public int Id { get; set; }
        public Nullable<decimal> MonthlyLeaves { get; set; }
        public Nullable<System.TimeSpan> MinWorkingHoursForFullDay { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursDay { get; set; }
        public Nullable<int> MinHoursCountsADays { get; set; }
        public Nullable<System.TimeSpan> HalfDayMinWorkHours { get; set; }
        public Nullable<bool> IsWorkingDaysWiseCalculation { get; set; }
        public Nullable<bool> IsAllMonthDaysWiseCalculation { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> monthStartDateDay { get; set; }
        public Nullable<int> monthendDateDay { get; set; }
        public Nullable<decimal> WorkingdaysPermonth { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
