//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousEduInfo
    {
        public int InfoId { get; set; }
        public Nullable<int> studentId { get; set; }
        public string nameOfSchool { get; set; }
        public Nullable<int> classId { get; set; }
        public string passingYear { get; set; }
        public string resonOfLeaving { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string contact { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
