//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAssigment
    {
        public int QuestionAssId { get; set; }
        public Nullable<int> qustId { get; set; }
        public Nullable<int> feedbackId { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual FeedbackFormMaster FeedbackFormMaster { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
