//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        public QuestionMaster()
        {
            this.QuestionAssigments = new HashSet<QuestionAssigment>();
            this.TblRatings = new HashSet<TblRating>();
        }
    
        public int QuestionId { get; set; }
        public Nullable<int> SectionsId { get; set; }
        public string QuestionName { get; set; }
        public Nullable<decimal> weightage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> firmid { get; set; }
    
        public virtual QuestionMaster QuestionMaster1 { get; set; }
        public virtual QuestionMaster QuestionMaster2 { get; set; }
        public virtual ICollection<QuestionAssigment> QuestionAssigments { get; set; }
        public virtual ICollection<TblRating> TblRatings { get; set; }
        public virtual TblSection TblSection { get; set; }
    }
}
