//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryStructure
    {
        public SalaryStructure()
        {
            this.Structurepermissions = new HashSet<Structurepermission>();
            this.CoumputedValues = new HashSet<CoumputedValue>();
            this.StaffCTCs = new HashSet<StaffCTC>();
            this.VariableSettings = new HashSet<VariableSetting>();
        }
    
        public int Id { get; set; }
        public string StuctureName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FirmId { get; set; }
    
        public virtual ICollection<Structurepermission> Structurepermissions { get; set; }
        public virtual ICollection<CoumputedValue> CoumputedValues { get; set; }
        public virtual ICollection<StaffCTC> StaffCTCs { get; set; }
        public virtual ICollection<VariableSetting> VariableSettings { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
