//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryVariable
    {
        public int tranId { get; set; }
        public Nullable<int> ctcId { get; set; }
        public Nullable<int> variableId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> persentage { get; set; }
        public string description { get; set; }
        public string editedBy { get; set; }
        public Nullable<System.DateTime> editedDate { get; set; }
        public Nullable<int> firmId { get; set; }
        public string Payheadtype { get; set; }
        public string EarnDeduct { get; set; }
        public string CalculationType { get; set; }
        public string ValueType { get; set; }
        public string VariableName { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<int> tranMonth { get; set; }
        public Nullable<int> tranYear { get; set; }
        public Nullable<int> monthlyDetailId { get; set; }
    
        public virtual StaffCTC StaffCTC { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
