//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMaster
    {
        public ShiftMaster()
        {
            this.ShiftHistories = new HashSet<ShiftHistory>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int shiftId { get; set; }
        public string shiftName { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<bool> isDateChange { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<System.TimeSpan> TotolDuration { get; set; }
    
        public virtual ICollection<ShiftHistory> ShiftHistories { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
