//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEducation
    {
        public int eduId { get; set; }
        public Nullable<int> degreeId { get; set; }
        public Nullable<int> degreeSubId { get; set; }
        public Nullable<int> addmissionYear { get; set; }
        public Nullable<int> passingYear { get; set; }
        public Nullable<decimal> persentage { get; set; }
        public Nullable<int> staffId { get; set; }
        public string university { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual DegreeSubject DegreeSubject { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
