//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.AdvanceEMIs = new HashSet<AdvanceEMI>();
            this.AdvanceRequests = new HashSet<AdvanceRequest>();
            this.AttendanceRequests = new HashSet<AttendanceRequest>();
            this.Bonus = new HashSet<Bonu>();
            this.CompansationRequests = new HashSet<CompansationRequest>();
            this.CompansationRequests1 = new HashSet<CompansationRequest>();
            this.CompansationTrans = new HashSet<CompansationTran>();
            this.ComputerAssingeds = new HashSet<ComputerAssinged>();
            this.LeaveBalances = new HashSet<LeaveBalance>();
            this.LeaveBalances1 = new HashSet<LeaveBalance>();
            this.LeavePassbooks = new HashSet<LeavePassbook>();
            this.LeaveRecordNews = new HashSet<LeaveRecordNew>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.notices = new HashSet<notice>();
            this.OptionalHolidayTrans = new HashSet<OptionalHolidayTran>();
            this.ShiftHistories = new HashSet<ShiftHistory>();
            this.Staff1 = new HashSet<Staff>();
            this.StaffDesignations = new HashSet<StaffDesignation>();
            this.StaffDocuments = new HashSet<StaffDocument>();
            this.StaffEducations = new HashSet<StaffEducation>();
            this.Structurepermissions = new HashSet<Structurepermission>();
            this.TblAllowTransactions = new HashSet<TblAllowTransaction>();
            this.TblAverageTimes = new HashSet<TblAverageTime>();
            this.TblAverageTimeForAttendanceSheets = new HashSet<TblAverageTimeForAttendanceSheet>();
            this.TblFormAssignments = new HashSet<TblFormAssignment>();
            this.TblFormEvaluators = new HashSet<TblFormEvaluator>();
            this.TblFormEvaluators1 = new HashSet<TblFormEvaluator>();
            this.TblLeaveRecords = new HashSet<TblLeaveRecord>();
            this.TblLoginRecords = new HashSet<TblLoginRecord>();
            this.TblNetDurationUsersNames = new HashSet<TblNetDurationUsersName>();
            this.TblRatings = new HashSet<TblRating>();
            this.WorkExperiances = new HashSet<WorkExperiance>();
            this.Reportings = new HashSet<Reporting>();
            this.Reportings1 = new HashSet<Reporting>();
            this.StaffCTCs = new HashSet<StaffCTC>();
            this.MonthlyAttenDetails = new HashSet<MonthlyAttenDetail>();
            this.TblOvertimeCalculates = new HashSet<TblOvertimeCalculate>();
        }
    
        public int staffId { get; set; }
        public string staffCode { get; set; }
        public string schoolCode { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string tempAddress { get; set; }
        public Nullable<int> tempCityId { get; set; }
        public string tempPincode { get; set; }
        public string tempArea { get; set; }
        public string perAddress { get; set; }
        public Nullable<int> perCityId { get; set; }
        public string perPincode { get; set; }
        public string perArea { get; set; }
        public Nullable<int> gender { get; set; }
        public string passportPhoto { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> castId { get; set; }
        public Nullable<int> subCastId { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string userId { get; set; }
        public string emergencyContact1 { get; set; }
        public string emergencyContact2 { get; set; }
        public string emergencyContact3 { get; set; }
        public Nullable<System.DateTime> joingDate { get; set; }
        public Nullable<int> designationId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> deptId { get; set; }
        public Nullable<int> reportingId { get; set; }
        public Nullable<decimal> leavesOpeningBalance { get; set; }
        public Nullable<int> enrollNumber { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<decimal> compansationOpeningBalance { get; set; }
        public string PAN { get; set; }
        public string PF { get; set; }
        public Nullable<System.DateTime> probation { get; set; }
        public Nullable<System.DateTime> conformationDate { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> inActiveResionId { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> lastWorkingDate { get; set; }
        public string emailReportingTo { get; set; }
        public string netDurationUserName { get; set; }
        public Nullable<bool> isMarried { get; set; }
        public string Languageknown { get; set; }
        public string Adharcardno { get; set; }
        public string VoteridNo { get; set; }
        public string Licence { get; set; }
        public string ReferalDetail { get; set; }
        public string Nationality { get; set; }
        public string Bloodgroup { get; set; }
        public string Personalmail { get; set; }
        public string Caste { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string CompanyId { get; set; }
    
        public virtual ICollection<AdvanceEMI> AdvanceEMIs { get; set; }
        public virtual ICollection<AdvanceRequest> AdvanceRequests { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AttendanceRequest> AttendanceRequests { get; set; }
        public virtual ICollection<Bonu> Bonus { get; set; }
        public virtual ICollection<CompansationRequest> CompansationRequests { get; set; }
        public virtual ICollection<CompansationRequest> CompansationRequests1 { get; set; }
        public virtual ICollection<CompansationTran> CompansationTrans { get; set; }
        public virtual ICollection<ComputerAssinged> ComputerAssingeds { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual InActiveResion InActiveResion { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances { get; set; }
        public virtual ICollection<LeaveBalance> LeaveBalances1 { get; set; }
        public virtual ICollection<LeavePassbook> LeavePassbooks { get; set; }
        public virtual ICollection<LeaveRecordNew> LeaveRecordNews { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<notice> notices { get; set; }
        public virtual ICollection<OptionalHolidayTran> OptionalHolidayTrans { get; set; }
        public virtual ICollection<ShiftHistory> ShiftHistories { get; set; }
        public virtual ShiftMaster ShiftMaster { get; set; }
        public virtual ICollection<Staff> Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual ICollection<StaffDesignation> StaffDesignations { get; set; }
        public virtual ICollection<StaffDocument> StaffDocuments { get; set; }
        public virtual ICollection<StaffEducation> StaffEducations { get; set; }
        public virtual ICollection<Structurepermission> Structurepermissions { get; set; }
        public virtual ICollection<TblAllowTransaction> TblAllowTransactions { get; set; }
        public virtual ICollection<TblAverageTime> TblAverageTimes { get; set; }
        public virtual ICollection<TblAverageTimeForAttendanceSheet> TblAverageTimeForAttendanceSheets { get; set; }
        public virtual ICollection<TblFormAssignment> TblFormAssignments { get; set; }
        public virtual ICollection<TblFormEvaluator> TblFormEvaluators { get; set; }
        public virtual ICollection<TblFormEvaluator> TblFormEvaluators1 { get; set; }
        public virtual ICollection<TblLeaveRecord> TblLeaveRecords { get; set; }
        public virtual ICollection<TblLoginRecord> TblLoginRecords { get; set; }
        public virtual ICollection<TblNetDurationUsersName> TblNetDurationUsersNames { get; set; }
        public virtual ICollection<TblRating> TblRatings { get; set; }
        public virtual ICollection<WorkExperiance> WorkExperiances { get; set; }
        public virtual ICollection<Reporting> Reportings { get; set; }
        public virtual ICollection<Reporting> Reportings1 { get; set; }
        public virtual ICollection<StaffCTC> StaffCTCs { get; set; }
        public virtual ICollection<MonthlyAttenDetail> MonthlyAttenDetails { get; set; }
        public virtual ICollection<TblOvertimeCalculate> TblOvertimeCalculates { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
