//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffCTC
    {
        public StaffCTC()
        {
            this.GeneratedSalaries = new HashSet<GeneratedSalary>();
            this.SalaryVariables = new HashSet<SalaryVariable>();
        }
    
        public int ctcId { get; set; }
        public Nullable<decimal> ctc { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<System.DateTime> incrementDate { get; set; }
        public string status { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string narration { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> structId { get; set; }
    
        public virtual ICollection<GeneratedSalary> GeneratedSalaries { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual SalaryStructure SalaryStructure { get; set; }
        public virtual ICollection<SalaryVariable> SalaryVariables { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
