//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDesignation
    {
        public int tranId { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> designationId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
