//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAllowTransaction
    {
        public int AllowTranId { get; set; }
        public Nullable<int> AllowId { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<int> firmid { get; set; }
        public string AdminRemark { get; set; }
        public string status { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string ApprovedBy { get; set; }
        public string StaffRemark { get; set; }
        public Nullable<System.DateTime> Expensedate { get; set; }
        public string transactionType { get; set; }
    
        public virtual TblAllowance TblAllowance { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
