//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAllowance
    {
        public TblAllowance()
        {
            this.TblAllowTransactions = new HashSet<TblAllowTransaction>();
        }
    
        public int AllowanceId { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AllowRemark { get; set; }
    
        public virtual ICollection<TblAllowTransaction> TblAllowTransactions { get; set; }
    }
}
