//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventLog
    {
        public int Id { get; set; }
        public string SysUsername { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string Logtype { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string NetUsername { get; set; }
        public Nullable<int> Firmid { get; set; }
    }
}
