//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmailConfig
    {
        public int EmailConfigId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string SMTPPortNo { get; set; }
        public string HostName { get; set; }
        public Nullable<int> firmid { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string extraColumn { get; set; }
    }
}
