//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeaveRecord
    {
        public TblLeaveRecord()
        {
            this.LeavePassbooks = new HashSet<LeavePassbook>();
        }
    
        public int LeaveRecordId { get; set; }
        public Nullable<int> LevetypeIds { get; set; }
        public Nullable<int> staffids { get; set; }
        public Nullable<decimal> totalLeaves { get; set; }
        public Nullable<bool> IsActiveLeave { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> firmsId { get; set; }
    
        public virtual ICollection<LeavePassbook> LeavePassbooks { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
