//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLoginCounter
    {
        public int LcounterId { get; set; }
        public Nullable<int> Lfirmid { get; set; }
        public Nullable<int> Lcounter { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
