//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOvertimeCalculate
    {
        public int OvertimeCalId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> FirmId { get; set; }
        public Nullable<int> calMonthId { get; set; }
        public Nullable<decimal> PerHour { get; set; }
        public Nullable<bool> Overtime { get; set; }
        public Nullable<bool> Undertime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
