//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRating
    {
        public int RatingId { get; set; }
        public Nullable<int> qusmasteId { get; set; }
        public Nullable<int> EmployeId { get; set; }
        public Nullable<decimal> ratingper { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> formid { get; set; }
        public Nullable<int> evaluId { get; set; }
    
        public virtual FeedbackFormMaster FeedbackFormMaster { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
