//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSpecifiedFormula
    {
        public int FormulaId { get; set; }
        public Nullable<int> FormulaVariableId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<decimal> FromAmount { get; set; }
        public Nullable<decimal> AmountUpto { get; set; }
        public Nullable<bool> SlabType { get; set; }
        public Nullable<decimal> ValueBasis { get; set; }
        public Nullable<int> FirmId { get; set; }
        public string ComputeName { get; set; }
        public string Specifiedformula { get; set; }
    
        public virtual VariableSetting VariableSetting { get; set; }
    }
}
