//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSection
    {
        public TblSection()
        {
            this.QuestionMasters = new HashSet<QuestionMaster>();
        }
    
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> firmid { get; set; }
    
        public virtual ICollection<QuestionMaster> QuestionMasters { get; set; }
    }
}
