//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryCalculateRule
    {
        public int CalculateId { get; set; }
        public string CalculateBy { get; set; }
        public Nullable<int> firmid { get; set; }
    }
}
