//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUniversal
    {
        public int UniversalId { get; set; }
        public string UniIdFirm { get; set; }
        public string UniIdEmployee { get; set; }
        public Nullable<bool> UniIdIsActive { get; set; }
    }
}
