//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainigId { get; set; }
        public string Topic { get; set; }
        public string TrainerName { get; set; }
        public Nullable<int> TrainerDept { get; set; }
        public string EgibilityCriteria { get; set; }
        public string Duration { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> TrainingDateStart { get; set; }
        public string TrainingStartTime { get; set; }
        public Nullable<int> NoofAttendant { get; set; }
        public string TrainingType { get; set; }
        public string TrainingRepetition { get; set; }
        public string Narration { get; set; }
        public string TrainingContent { get; set; }
        public string TrainingLocation { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> FirmId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> TrainingEndDate { get; set; }
        public string TrainingEndTime { get; set; }
        public Nullable<bool> Done { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
