//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingFeedback
    {
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public string Feedback { get; set; }
        public string Status { get; set; }
        public Nullable<int> FirmId { get; set; }
    }
}
