//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarienceReport
    {
        public int varId { get; set; }
        public string Daptname { get; set; }
        public Nullable<int> TotalManpower { get; set; }
        public Nullable<decimal> trgManHrs { get; set; }
        public Nullable<decimal> short_excess { get; set; }
        public Nullable<decimal> targetMonth { get; set; }
        public Nullable<decimal> week1 { get; set; }
        public Nullable<decimal> week2 { get; set; }
        public Nullable<decimal> week3 { get; set; }
        public Nullable<decimal> week4 { get; set; }
        public Nullable<decimal> totalAchiveHrs { get; set; }
        public Nullable<decimal> varience { get; set; }
        public Nullable<int> MonthNo { get; set; }
        public Nullable<int> YearNo { get; set; }
        public Nullable<int> firmid { get; set; }
        public Nullable<int> deptid { get; set; }
    
        public virtual VarienceReport VarienceReport1 { get; set; }
        public virtual VarienceReport VarienceReport2 { get; set; }
    }
}
