//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableSetting
    {
        public VariableSetting()
        {
            this.GeneratedSalaryVariables = new HashSet<GeneratedSalaryVariable>();
            this.InActiveResions = new HashSet<InActiveResion>();
            this.TblGratuityCalculations = new HashSet<TblGratuityCalculation>();
            this.TblSpecifiedFormulas = new HashSet<TblSpecifiedFormula>();
            this.VariableSettings1 = new HashSet<VariableSetting>();
            this.VariableSettings11 = new HashSet<VariableSetting>();
            this.VariableSettings12 = new HashSet<VariableSetting>();
        }
    
        public int variableId { get; set; }
        public string VariableName { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isCalculateFromCTC { get; set; }
        public Nullable<int> calculateFrom1 { get; set; }
        public Nullable<int> calculateFrom2 { get; set; }
        public Nullable<int> calculateFrom3 { get; set; }
        public Nullable<decimal> persentage { get; set; }
        public Nullable<bool> isEarnings { get; set; }
        public Nullable<bool> isDuductions { get; set; }
        public Nullable<decimal> graterThanLimit { get; set; }
        public Nullable<decimal> graterLimitAmt { get; set; }
        public Nullable<decimal> lessThanLimit { get; set; }
        public Nullable<decimal> lessLimitAmt { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> deptId { get; set; }
        public Nullable<int> firmId { get; set; }
        public Nullable<int> SalaryStructId { get; set; }
        public string payheadtype { get; set; }
        public string affectnetsal { get; set; }
        public string statuspay { get; set; }
        public string gratuity { get; set; }
        public string Under { get; set; }
        public string Calculationtype { get; set; }
        public string payslipname { get; set; }
        public string calculatemulti { get; set; }
        public string incometaxdetails { get; set; }
        public string calculationperiod { get; set; }
        public string productiontype { get; set; }
        public string attendaceleave { get; set; }
        public string Roundingmethod { get; set; }
        public Nullable<int> roundinglimit { get; set; }
        public string EarnDeduct { get; set; }
        public string PerValue { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ComputeOn { get; set; }
        public string statutoryPayType { get; set; }
        public string statutoryRegiNo { get; set; }
    
        public virtual ICollection<GeneratedSalaryVariable> GeneratedSalaryVariables { get; set; }
        public virtual ICollection<InActiveResion> InActiveResions { get; set; }
        public virtual SalaryStructure SalaryStructure { get; set; }
        public virtual ICollection<TblGratuityCalculation> TblGratuityCalculations { get; set; }
        public virtual ICollection<TblSpecifiedFormula> TblSpecifiedFormulas { get; set; }
        public virtual ICollection<VariableSetting> VariableSettings1 { get; set; }
        public virtual VariableSetting VariableSetting1 { get; set; }
        public virtual ICollection<VariableSetting> VariableSettings11 { get; set; }
        public virtual VariableSetting VariableSetting2 { get; set; }
        public virtual ICollection<VariableSetting> VariableSettings12 { get; set; }
        public virtual VariableSetting VariableSetting3 { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
