//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edueTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weekend
    {
        public int weekendId { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public string day { get; set; }
        public Nullable<int> deptId { get; set; }
        public Nullable<int> firmId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual FirmInfo FirmInfo { get; set; }
    }
}
